### ISSUE TITLE
Obtain raw data from twitter

### ISSUE THREAD

**Issue by LenzoM** [joebrew/vilaweb#1]
Dear Joe,

thank you very much for your time and reports you prepare. They are truly awesome.
My question is: how do you obtain the raw data from a closed code app such as twitter? 
As far as I see you program using R. The code is compatible for python? 
Which program do you use? Jupyter, or visual studio code?

Thank you for your time!

**Comment by sciencegraph** [comment]
I guess Joe is using RStudio and since it is R code it is not compatible with python.

**Comment by joebrew** [comment]
Hi @LenzoM , apologies for the delay.

There are two ways I get tweets.
1. Using the `rtweet` package. It's a great, well documented package. https://rtweet.info/ The only disadvantage is that it (a) requires you first set up a developers account (ie, get credentials for the API) and (b) it cannot (at least in its free version) retreive tweets older than 3200 tweets back.

2. Using the python "twint" package. This is a bit more "hacky" than rtweet, using scraping rather than the API. The disadvantage: it's slow. The advantage - you can go further back in time! https://github.com/twintproject/twint
